apiVersion: v1
data:
  fortuna.conf: |
    server {
            listen 8080;
            server_name nginx-apigw.mw-cz.svc.cluster.local;

            # INFRA-12046
            add_header Cache-Control no-store;
            add_header Pragma no-cache;

            resolver XXXXX valid=60s;

            proxy_http_version 1.1;
            location /bm {
                    set $upstream svc-bonus-manager.bm-cz.svc.cluster.local:8080;
                    proxy_read_timeout 45s;
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-Prefix /bm/;
                    proxy_set_header X-Forwarded-Proto https;
                    proxy_set_header X-Forwarded-Port 443;
                    rewrite ^/bm/$ https://$host/bm/swagger-ui.html redirect;
                    if ($request_uri ~* "/bm/(.*)") {
                       proxy_pass http://$upstream/$1;
                    }
            }
            location /pal {
                    set $upstream svc-playtech-adaptation-layer.mw-cz.svc.cluster.local:8080;
                    proxy_read_timeout 45s;
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-Prefix /pal/;
                    proxy_set_header X-Forwarded-Proto https;
                    proxy_set_header X-Forwarded-Port 443;
                    rewrite ^/pal/$ https://$host/pal/swagger-ui.html redirect;
                    if ($request_uri ~* "/pal/(.*)") {
                       proxy_pass http://$upstream/$1;
                    }
            }
            location /pams {
                    set $upstream svc-pams.mw-cz.svc.cluster.local:8080;
                    proxy_read_timeout 45s;
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-Prefix /pams/;
                    proxy_set_header X-Forwarded-Proto https;
                    proxy_set_header X-Forwarded-Port 443;
                    rewrite ^/pams/$ https://$host/pams/swagger-ui.html redirect;
                    if ($request_uri ~* "/pams/(.*)") {
                       proxy_pass http://$upstream/$1;
                    }
            }
    }
  healthchecksimple.html: itworks
  nginx.conf: |
    user nginx;
    worker_processes 4;

    daemon off;

    error_log  /var/log/nginx/error.log debug;
    pid        /var/cache/nginx/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format main escape=json '{ "remote_addr": "$remote_addr", "remote_user": "$remote_user", "srctime": "$time_iso8601", "request": "$request", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "http_referer": "$http_referer", "user_agent": "$http_user_agent", "http_x_forwarded_for": "$http_x_forwarded_for", "upstream_cache_status": "$upstream_cache_status", "request_time": "$request_time", "upstream_response_time": "$upstream_response_time", "request_body": "$request_body", "set_cookie": "$sent_http_set_cookie", "http_cookie": "$http_cookie", "request_id": "$request_id" }';

      access_log /var/log/nginx/access.log main;
      # Just for debugging purpose - please uncomment
      # ssl_ciphers "AES128-GCM-SHA256:AES128:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
      # proxy_ssl_ciphers  "AES128-GCM-SHA256:AES128:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";


      ssl_session_cache shared:SSL:10m;
      ssl_protocols TLSv1.2;
      ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

      server_tokens off;

      sendfile on;
      keepalive_timeout 65;
      gzip on;
      gzip_http_version 1.1;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types *;
      gzip_disable "MSIE [1-6]\.(?!.*SV1)";
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cache-space:100m max_size=1024m inactive=1h;
      client_max_body_size 20M;

      include /etc/nginx/conf.d/fortuna.conf;

      # Metrics for Prometheus
      server {
            listen localhost:8180;
            location /stub_status {
                stub_status;
            }
      }
    }
  robots.txt: |-
    User-Agent: *
    Disallow: *
    Crawl-delay: 20
kind: ConfigMap
metadata:
  name: nginx-apigw
  namespace: mw-cz

