- name: Set global variables
  set_fact:
    keycloak_version: "12.0.2"
    pg_jdbc_version: "42.2.18"
    db_connection_string: "localhost:5432/keycloak"
    db_username: "keycloak"
    db_password: "keycloak12345"
    username: "keycloak"
    adminpwd: "admin"
    lvdata_size: "20G"