- name: Set global variables
  set_fact:
    virbr: "8"
    netsuffix: "21" 
    hostname: "registry"
    domain: "lab.local"
    mem: "2G"
    ipaserver: "freeipa.lab.local"
    nfsserver: "nfsnode.lab.local"
    home_export: "/nfsvg/home"
    ipaip: "10.1.8.10"
    ldapbase: "dc=lab,dc=local"
    svcadmin: "admin"
    adminpwd: "admin123"
    template: "t_centos7"
    template_dir: "/data/templates"
    vms_dir: "/data/vms"
    rootvg_size: 30


- name: Set ip
  set_fact:
    ip: "10.1.{{ virbr  }}.{{ netsuffix }}"



- name: Set FQDN
  set_fact:
    fqdn: "{{ hostname }}.{{ domain }}"

- name: Set REALM
  set_fact: 
    realm: "{{ domain|upper }}"

- name: Set disksize
  set_fact: 
    disksize: "21G"
