apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: krakend
    application: krakend
  name: krakend
  selfLink: /api/v1/namespaces/krakend/services/krakend
spec:
  externalIPs:
  - 10.1.16.130
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: krakend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
