---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Create snapshot for the host
    shell: virsh snapshot-create-as --domain {{ fqdn }} --name "before FreeIPA installation"

  - name: Start machine
    shell: virsh start {{ fqdn }}
    ignore_errors: yes

  - name: "Create ansible group for new hosts"
    add_host: name="{{ ip }}" groups=newhost

- hosts: newhost
  become: true
  gather_facts: no
  tasks:
  - pause:
      seconds: 25

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Setup temporary external DNS
    shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

  - name: Install prereq packages
    shell: yum install ipa-server ipa-server-dns -y

  - name: hostnamectl workarround 
    shell: rm -f /usr/bin/hostnamectl ; ln -s /usr/bin/true /usr/bin/hostnamectl

  - name: Allow https on firewalld
    shell: firewall-cmd --add-service=https --add-service=ldap --add-service=ldaps --add-service=kerberos --add-service=kpasswd --add-service=dns --permanent ; firewall-cmd --reload

  - name: Setup temporary external DNS
    shell: echo "nameserver {{ ip }}" > /etc/resolv.conf
 
  - name: Customize /etc/hosts
    shell: sed -i -E "/{{ ip }}/d" /etc/hosts ; echo "{{ ip }} {{ fqdn }} {{ hostname }}" >> /etc/hosts

  - name: Install ipa server
    shell: ipa-server-install --ip-address={{ ip }} --hostname={{ fqdn }} --realm={{ realm }} --domain={{ domain }} \
           --ds-password={{ adminpwd }} --admin-password={{ adminpwd }} --mkhomedir --setup-dns --unattended --no-forwarders
