---
- hosts: freeipa.lab.syscallx86.com
  become: true
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Get the krb5 ticket
    shell: echo "{{ adminpwd }}" | kinit {{ svcadmin }}

  - name: Add groups
    shell: ipa group-add {{ item.groupname }} --gid={{ item.gid }}
    loop:
      - { groupname: 'stuff', gid: '1100' }
      - { groupname: 'k8s-cluster-admin', gid: '1111' }
      - { groupname: 'k8s-cluster-user', gid: '1112' }
      - { groupname: 'ocp-cluster-admin', gid: '1121' }
      - { groupname: 'ocp-cluster-user', gid: '1122' }
      - { groupname: 'simple-admin', gid: '1151' }
      - { groupname: 'simple-user', gid: '1152' }
    ignore_errors: yes

  - name: Add users
    shell: ipa user-add {{ item.username }} --gid=1100 --homedir=/nfshome/{{ item.username }} --random --shell=/bin/bash --first={{ item.first }} --last={{ item.last }}
    loop:
      - { username: 'veldrane', first: 'Veldrane', last: 'Veldranovic' }
      - { username: 'valor', first: 'Valor', last: 'Valorovic' }
      - { username: 'jdvorak', first: 'Jan', last: 'Dvorak' }
      - { username: 'mnovak', first: 'Martin', last: 'Novak' }
      - { username: 'ddvorak', first: 'David', last: 'Dvorak' }
    ignore_errors: yes

- hosts: nfsnode.lab.syscallx86.com
  become: true
  gather_facts: no
  tasks:

   - name: Create home dir for users
     shell: mkdir /nfsvg/home/{{ item.username }} && cp -r /etc/skel /nfsvg/home/{{ item.username }} && chown {{ item.username }}:stuff -R /nfsvg/home/{{ item.username }}
     loop:
      - { username: 'veldrane', first: 'Veldrane', last: 'Veldranovic' }
      - { username: 'valor', first: 'Valor', last: 'Valorovic' }
      - { username: 'jdvorak',  first: 'Jan', last: 'Dvorak' }
      - { username: 'mnovak',  first: 'Martin', last: 'Novak' }
      - { username: 'ddvorak', first: 'David', last: 'Dvorak' }
     ignore_errors: yes

   - name: restore selinux context
     shell: restorecon -R /nfsvg/home
