apiVersion: v1
data:
  krakend.json: |-
    {
      "version": 2,
      "extra_config": {
        "github_com/devopsfaith/krakend-httpsecure": {
          "allowed_hosts": [
            "krakend.lab.local"
          ],
          "ssl_proxy_headers": {}
        },
          "github_com/devopsfaith/krakend-metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":8090"
        },
        "github_com/devopsfaith/krakend-opencensus": {
          "sample_rate": 100,
          "reporting_period": 1,
          "exporters": {
            "prometheus": {
              "port": 9090
            }
          }
        }
      },
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "json",
      "name": "apigw",
      "endpoints": [
        {
          "endpoint": "/token",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/token",
              "encoding": "json",
              "host": [
                "http://nginx.keystore.svc.cluster.local:8080"
              ]
            }
          ],
          "extra_config": {
            "github.com/devopsfaith/krakend-jose/signer": {
              "alg": "HS256",
              "kid": "artices",
              "keys-to-sign": ["access_token", "refresh_token"],
              "jwk-url": "http://nginx.keystore.svc:8080/articles-hs256.json",
              "disable_jwk_security": true
            }
          }
        },
        {
          "endpoint": "/simple/articles",
          "method": "GET",
          "extra_config": {
              "github.com/devopsfaith/krakend-jose/validator": {
                  "alg": "RS256",
                  "roles_key": "groups",
                  "roles": ["simple-admin","simple-user"],
                  "jwk-url": "https://secure-keycloak-keycloak.route.local/auth/realms/lab/protocol/openid-connect/certs",
                  "disable_jwk_security": true
              }
           },
          "backend": [
            {
              "url_pattern": "/articles",
              "encoding": "json",
              "is_collection": true,
              "extra_config": {
                  "github.com/devopsfaith/krakend/proxy": {
                      "flatmap_filter": [
                          {
                              "type": "del",
                              "args": ["collection.*.Id"]
                          }
                      ]
                  }
              }, 
              "host": [
                "http://simpleapi.simple.svc.cluster.local:8080"
              ]
            }
          ]
        },
        {
          "endpoint": "/simple/article",
          "method": "POST",
          "extra_config": {
              "github.com/devopsfaith/krakend-jose/validator": {
                  "alg": "RS256",
                  "roles_key": "groups",
                  "roles": ["simple-admin"],
                  "jwk-url": "https://secure-keycloak-keycloak.route.local/auth/realms/lab/protocol/openid-connect/certs",
                  "disable_jwk_security": true
              }
          },
          "backend": [
            {
              "url_pattern": "/article",
              "encoding": "json",
              "method": "POST",
              "host": [
                "http://simpleapi.simple.svc.cluster.local:8080"
              ]
            }
          ]
        },
        {
          "endpoint": "/simple/article/{id}",
          "output_encoding": "no-op",
          "method": "GET",
          "headers_to_pass": [
            "*"
          ],
          "backend": [
            {
              "method": "GET",
              "url_pattern": "/article/{id}",
              "host": [
                "http://simpleapi.simple.svc.cluster.local:8080"
              ],
              "encoding": "no-op"
            }
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  selfLink: /api/v1/namespaces/krakend/configmaps/config
