---
- hosts: localhost
  become: false
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml
  
  - name: Create temp directory for download
    shell: mkdir temp
    ignore_errors: yes

  - name: Copy keycloak to temp
    shell: cp archives/keycloak-{{ keycloak_version }}.tar.gz temp/

  - name: Download postgre jdbc client
    shell: curl https://jdbc.postgresql.org/download/postgresql-{{ pg_jdbc_version }}.jar -o temp/postgresql-{{ pg_jdbc_version }}.jar

  - name: Prepare keycloak template coniguration
    template:
      src: include/standalone.xml.{{ keycloak_version }}.template
      dest: temp/standalone.xml

  - name: Prepare module.xml template
    template:
      src: include/module.xml.template
      dest: temp/module.xml

  - name: Prepare keycloak systemd template
    template:
      src: include/keycloak.service.template
      dest: temp/keycloak.service

- hosts: keycloak01-k8s01-poc
  become: true
  gather_facts: no
  tasks:
  
  - name: Set variables
    include: include/_setup_vars.yaml 

  - name: Copy binaries to /tmp
    copy:
      src: temp/{{ item }}
      dest: /tmp
    with_items:
      - postgresql-{{ pg_jdbc_version }}.jar
      - keycloak-{{ keycloak_version }}.tar.gz
      - standalone.xml
      - module.xml
      - keycloak.service

  - name: Check fs
    shell: cat /etc/fstab| grep /data | grep -v -E '^#' | cut -d " " -f2
    register: data_lv
  
  - name: Create data_lv for postgresql
    shell: mkdir /data && lvcreate -n lv_data -L{{ lvdata_size }} vg_system && mkfs.ext4 /dev/mapper/vg_system-lv_data
    when: data_lv.stdout == ""

  - name: Add data_lv to fstab
    shell: echo '/dev/mapper/vg_system-lv_data /data ext4 defaults 0 0' >> /etc/fstab
    when: data_lv.stdout == ""

  - name: Mount fs data
    shell: mount /data
    when: data_lv.stdout == ""

  - name: Install postgresql
    shell: apt-get -y install postgresql
    ignore_errors: yes
  
  - name: Create postgresql subdir
    shell: mkdir /data/postgresql

  - name: Stop postgresql
    shell: systemctl stop postgresql

  - name: Backup pgsql dir to tmp location
    shell: cd /var/lib/postgresql/12/main ; tar cvfz /tmp/pgdata.tgz .

  - name: Restore pgsql dir to new /data/postgresql location
    shell: cd /data/postgresql ; tar xvfz /tmp/pgdata.tgz . ; rm -f /tmp/pgdata.tgz
  
  - name: Change data dir in postgresql config
    shell: sed -i -E 's/\/var\/lib\/postgresql\/12\/main/\/data\/postgresql/g' /etc/postgresql/12/main/postgresql.conf

  - name: Chown postgresql data
    shell: chown -R postgres:postgres /data/postgresql

  - name: Start postgresql
    shell: systemctl start postgresql


- hosts: localhost
  become: false
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Delete temp file
    shell: rm -rf temp