---
- hosts: keycloak01-k8s01-poc
  become: true
  gather_facts: no
  tasks:
  
  - name: Set variables
    include: include/_setup_vars.yaml
  
  - name: Add admin user to master realm
    shell: cd /opt/keycloak/current/bin && ./add-user-keycloak.sh -r master -u admin -p {{ adminpwd }}