- name: Set global variables
  set_fact:
    virbr: "16"
    netsuffix: "81" 
    hostname: "node81"
    domain: "lab.local"
    mem: "4G"
    ipaserver: "freeipa.lab.local"
    ipaip: "10.1.8.10"
    ldapbase: "dc=lab,dc=local"
    svcadmin: "admin"
    adminpwd: "admin123"
    template: "t_centos7"
    template_dir: "/data/templates"
    vms_dir: "/data/vms"

- name: Set ip
  set_fact:
    ip: "10.1.{{ virbr  }}.{{ netsuffix }}"



- name: Set FQDN
  set_fact:
    fqdn: "{{ hostname }}.{{ domain }}"

- name: Set REALM
  set_fact: 
    realm: "{{ domain|upper }}"
