- name: Set global variables
  set_fact:
    virbr: "16"
    netsuffix: "35" 
    hostname: "node35"
    domain: "lab.local"
    mem: "8G"
    ipaserver: "freeipa.lab.local"
    ipaip: "10.1.8.10"
    ldapbase: "dc=lab,dc=local"
    svcadmin: "admin"
    adminpwd: "admin123"
    template: "t_centos7"
    template_dir: "/data/templates"
    vms_dir: "/data/vms"
    rootvg_size: 30


- name: Set ip
  set_fact:
    ip: "10.1.{{ virbr  }}.{{ netsuffix }}"



- name: Set FQDN
  set_fact:
    fqdn: "{{ hostname }}.{{ domain }}"

- name: Set REALM
  set_fact: 
    realm: "{{ domain|upper }}"

- name: Set disksize
  set_fact: 
    disksize: "51G"

- name: Set ocp master
  set_fact:
    master: "node11.lab.local"

- name: Set user for elasticsearch
  set_fact:
    uid: "1008"
    gid: "1008"
    username: "elastic"
    groupname: "elastic"
    hostpath: "/elk/data"
    
