apiVersion: v1
data:
  krakend.json: |-
    {
      "version": 2,
      "extra_config": {
        "github_com/devopsfaith/krakend-httpsecure": {
          "allowed_hosts": [
            "krakend.lab.local"
          ],
          "ssl_proxy_headers": {}
        },
          "github_com/devopsfaith/krakend-metrics": {
          "collection_time": "60s",
          "proxy_disabled": false,
          "router_disabled": false,
          "backend_disabled": false,
          "endpoint_disabled": false,
          "listen_address": ":8090"
        },
        "github_com/devopsfaith/krakend-opencensus": {
          "sample_rate": 100,
          "reporting_period": 1,
          "exporters": {
            "prometheus": {
              "port": 9090
            }
          }
        }
      },
      "timeout": "3000ms",
      "cache_ttl": "300s",
      "output_encoding": "json",
      "name": "apigw",
      "endpoints": [
        {
          "endpoint": "/simple/articles",
          "output_encoding": "no-op",
          "method": "GET",
          "headers_to_pass": [
            "*"
          ],
          "backend": [
            {
              "method": "GET",
              "url_pattern": "/articles",
              "host": [
                "http://simpleapi.simple.svc.cluster.local:8080"
              ],
              "encoding": "no-op"
            }
          ]
        },
        {
          "endpoint": "/simple/article/{id}",
          "output_encoding": "no-op",
          "method": "GET",
          "headers_to_pass": [
            "*"
          ],
          "backend": [
            {
              "method": "GET",
              "url_pattern": "/article/{id}",
              "host": [
                "http://simpleapi.simple.svc.cluster.local:8080"
              ],
              "encoding": "no-op"
            }
          ]
        }
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2020-03-28T20:29:58Z
  name: config
  namespace: krakend
  resourceVersion: "1040142"
  selfLink: /api/v1/namespaces/krakend/configmaps/config
  uid: e49ee770-7132-11ea-9869-525400dc1209
