- name: Set global variables
  set_fact:
    virbr: "8"
    netsuffix: "23" 
    hostname: "keycloak"
    domain: "lab.local"
    mem: "2G"
    ipaserver: "freeipa.lab.local"
    ipaip: "10.1.8.10"
    nfsserver: "nfsnode.lab.local"
    home_export: "/nfsvg/home"
    ldapbase: "dc=lab,dc=local"
    svcadmin: "admin"
    adminpwd: "admin123"
    template: "t_centos7"
    template_dir: "/data/templates"
    vms_dir: "/data/vms"
    rootvg_size: 30

- name: Set Keycloak variables
  set_fact:
    keycloak_version: "12.0.2"
    pg_jdbc_version: "42.2.18"
    db_connection_string: "localhost:5432/keycloak"
    db_username: "keycloak"
    db_password: "keycloak12345"
    kcusername: "keycloak"
    kcadminpwd: "admin"
    lvdata_size: "5G"


- name: Set ip
  set_fact:
    ip: "10.1.{{ virbr  }}.{{ netsuffix }}"



- name: Set FQDN
  set_fact:
    fqdn: "{{ hostname }}.{{ domain }}"

- name: Set REALM
  set_fact: 
    realm: "{{ domain|upper }}"
