apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: elastic
    namespace: elastic
  spec:
    ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
    selector:
      statefulset.kubernetes.io/pod-name: elastic-0
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
