---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Create snapshot for the host
    shell: virsh snapshot-create-as --domain {{ fqdn }} --name "before Consul installation"
    ignore_errors: yes

  - name: "Create ansible group for new hosts"
    add_host: name="{{ ip }}" groups=newhost


- hosts: newhost
  become: true
  gather_facts: no
  tasks:


  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Setup firewall rules
    shell: firewall-cmd --permanent --add-port=6080/tcp --add-port 6080/tcp --add-port 8502/tcp --add-port 21000/tcp

  - name: Install yum utils
    shell: yum install -y yum-utils

  - name: Add hashicorp repo
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

  - name: Install yum consul and envoy proxy
    shell: yum install -y consul hashicorp-envoy.x86_64
  
  - name: Make certs dir
    shell: mkdir -p /etc/consul.d/certs ; chown R consul.consul /etc/consul.d

  - name: Mame Envoy dir
    shell: mkdir /etc/envoy

  - name: Copy consul client definition
    copy: 
      src: include/client.hcl
      dest: /etc/consul.d/
  
  - name: Copy webservice client definition
    copy:
      src: include/client.hcl
      dest: /etc/consul.d/

- hosts: localhost
  become: true
  gather_facts: no
  tasks:

  - name: Set variables
    include: include/_setup_vars.yaml

  - name: Delete snapshot for the host
    shell: virsh snapshot-delete --domain {{ fqdn }} --snapshotname "before Consul installation"

