allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: lowuid provides low uid run users
  name: lowuid
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 500
  uidRangeMin: 65534
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- keycloak
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
