apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: simpleapi
      application: simpleapi
    name: simpleapi
    namespace: simple
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentConfig: simpleapi
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: simpleapi
          deploymentConfig: simpleapi
        name: simpleapi
      spec:
        containers:
        - image: registry.lab.local/openshift/simpleapi:1.0
          imagePullPolicy: Always
          name: simpleapi
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

